#!/bin/bash 

#M_X=$(xdotool getmouselocation | awk '{gsub(".:","");print $1}')
#M_Y=$(xdotool getmouselocation | awk '{gsub(".:","");print $2}')
#	--geometry=100x100+"$M_X"+"$M_Y" \

if ! wmctrl -c "date_gate";then 
	yad \
	--title=Date_gate \
        --mouse \
	--close-on-unfocus \
	--window-icon="time-admin" \
	--sticky \
	--undecorated \
	--scale \
	--on-top \
	--no-buttons \
	--calendar
fi
