#!/bin/bash 

sudo echo "deb https://notesalexp.org/debian/bionic/ bionic main" >> /etc/apt/source.list
sudo apt-get install apt-transport-https
sudo apt-get update -oAcquire::AllowInsecureRepositories=true
sudo apt-get install notesalexp-keyring -oAcquire::AllowInsecureRepositories=true

sudo apt install obkey 
