#!/bin/bash 

wget -O ~/Downloads/gtkdialog.deb https://launchpad.net/~inameiname/+archive/ubuntu/stable/+files/gtkdialog_0.8.3-1~trusty0_amd64.deb

sudo dpkg -i ~/Downloads/gtkdialog.deb
sudo apt install -f
