#!/bin/bash 

echo "deb https://notesalexp.org/debian/bionic/ bionic main" | sudo tee /etc/apt/sources.list.d/notesalexp.list
sudo apt-get install apt-transport-https
sudo apt-get update -oAcquire::AllowInsecureRepositories=true
sudo apt-get install notesalexp-keyring -oAcquire::AllowInsecureRepositories=true

sudo apt install obkey 
