#!/bin/bash 

_B_BUTTON() {
echo '<button image-position="2" width-request="140" height-request="80">
	<width>48</width>
	<label>'${1}'</label>
	<input file icon="'${2}'"></input>
	<action>'${3}'</action>
</button>'
}

_S_BUTTON() {
echo '<button>
	<input file icon="'$1'"></input>
	<action>'$2'</action>
</button>'
}

export EXIT_DIALOG='
<window title="Gatter Session manager" icon-name="gnome-logout" resizable="false">
<vbox>
	<pixmap>
		<width>48</width>
		<input file icon="gatter"></input>
	</pixmap>
	<text use-markup="true"><label>"<span font='"'Terminus Bold 12'"'>Gatter Session Manager</span>"</label></text>
	<frame>
	<hbox>
		'"$(_B_BUTTON "PowerOff" "system-shutdown" "poweroff -h")"'
		'"$(_B_BUTTON "Suspend" "system-suspend" "lxtask")"'
		'"$(_B_BUTTON "Log Out" "system-log-out" "lxtask")"'
	</hbox>
	<hbox>
		'"$(_B_BUTTON "Reboot" "system-restart" "lxtask")"'
		'"$(_B_BUTTON "Hibernate" "system-hibernate" "lxtask")"'
		'"$(_B_BUTTON "Lock" "system-lock-screen" "lxtask")"'
	</hbox>
	</frame>
	<hbox homogeneous="true">
		'"$(_S_BUTTON "terminal" "x-terminal-emulator")"'
		'"$(_S_BUTTON "g-settings" "g-settings")"'
		'"$(_S_BUTTON "system-file-manager" "pcmanfm $HOME")"'
		'"$(_S_BUTTON "gtk-cancel" "EXIT:exit")"'
	</hbox>
</vbox>
</window>'

gtkdialog -c -p EXIT_DIALOG
